site_name: Robokassa Docs
site_url: https://rk-sales.github.io/docs/

theme:
  name: material
  language: ru
  palette:
    - scheme: default
      primary: white
      accent: blue

extra_css:
  - extra.css
  
plugins:
  - search
  - section-index
  
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Главная: index.md

  - Приём платежей:
      - Платёжные методы:
          - priem-platezhey/platezhnye-metody/index.md
          - Карты РФ: priem-platezhey/platezhnye-metody/cards-rf.md
          - Иностранные карты: priem-platezhey/platezhnye-metody/cards-foreign.md
          - СБП: priem-platezhey/platezhnye-metody/sbp.md
          - Sber Pay: priem-platezhey/platezhnye-metody/sberpay.md
          - T-Pay: priem-platezhey/platezhnye-metody/tpay.md
          - MTS Pay: priem-platezhey/platezhnye-metody/mts-pay.md
          - Alfa Pay: priem-platezhey/platezhnye-metody/alfa-pay.md
          - Yandex Pay (с двойным кэшбэком): priem-platezhey/platezhnye-metody/yandex-pay.md
          - Mir Pay (с двойным кэшбэком): priem-platezhey/platezhnye-metody/mir-pay.md
          - Оплата частями «Подели»: priem-platezhey/platezhnye-metody/podeli.md
          - Оплата частями «Yandex Split»: priem-platezhey/platezhnye-metody/yandex-split.md
          - Оплата частями «Мокка»: priem-platezhey/platezhnye-metody/mokka.md
          - Рассрочка / кредит ОТП-Банк: priem-platezhey/platezhnye-metody/otp-credit.md
          - Рассрочка через карту «Халва»: priem-platezhey/platezhnye-metody/halva.md
          - ЮMoney кошелёк: priem-platezhey/platezhnye-metody/yoomoney.md
      - Функции Robokassa:
          - priem-platezhey/funktsii/index.md
          - Мультибанкинг: priem-platezhey/funktsii/multibanking.md
          - Формирование ссылок на оплату: priem-platezhey/funktsii/payment-links.md
          - Холдирование платежей: priem-platezhey/funktsii/hold.md
          - Рекуррентные платежи (подписки): priem-platezhey/funktsii/recurring.md
          - Сплитование (деление платежей на разные компании): priem-platezhey/funktsii/split.md
          - Мультиаккаунт: priem-platezhey/funktsii/multiaccount.md
          - Брендирование платёжной формы: priem-platezhey/funktsii/branding.md
      - Чеки и ФЗ-54 (Фискализация платежей):
          - priem-platezhey/fz-54/index.md
          - Робочеки (Бесплатная Онлайн-Касса): priem-platezhey/fz-54/robocheki.md
          - Робокасса-Онлайн (Аренда облачной кассы): priem-platezhey/fz-54/robokassa-online.md
          - Робочеки СМЗ (Чеки для самозанятых): priem-platezhey/fz-54/robocheki-smz.md


  - Подключение:
      - Инструкция подключения для ИП: podklyuchenie/ip.md
      - Инструкция подключения для ООО: podklyuchenie/ooo.md
      - Инструкция подключения для СМЗ: podklyuchenie/smz.md
      - Требования к подключаемым веб-ресурсам:
          - Требования к сайтам: podklyuchenie/trebovaniya/sites.md
          - Требования к сообществу VK: podklyuchenie/trebovaniya/vk.md
          - Требования к Telegram‑каналу или боту: podklyuchenie/trebovaniya/telegram.md
          - Требования к мобильному приложению: podklyuchenie/trebovaniya/mobile-app.md
          
  - Инструкции и обучение:
      - Работа через ЛК (login.robokassa.ru):
          - Вывод и автовывод денежных средств: instructions/lk-robokassa/vyvod.md
          - Выставление разовой ссылки на оплату: instructions/lk-robokassa/dynamic-link.md
          - Выставление многоразовой ссылки на оплату: instructions/lk-robokassa/static-link.md
          - Выставление ссылок с регулярным списанием (подписка): instructions/lk-robokassa/sub-link.md
      - Работа через Мобильное Приложение (pwa.robokassa.ru):
          - Требования к мобильному приложению: instructions/app-robokassa/chiki.md

  - Интеграции: integratsii/index.md

  - Мобильное приложение Robokassa: mobile-app/index.md

